### ISSUE TITLE
System Updates

### ISSUE THREAD

**Issue by M4Lien** [M4Lien/schoolistan#1]
SDGFHDDEYR$%@#WDDDGHHDDD=

**Comment by alexwmsoft** [comment]
CYasQijhEmQoKpi0Nf0ltA==

**Comment by alexwmsoft** [comment]
The token is refreshed.

/3/f0ES72haltS576ru62Hjf0phN63/hYMyxCMcDk6VtT8lBUlqCgtGG2NzER2RXUM3CmjBeE+bV83fzrY2xoNrmwEBTrIwuTh/efORH0m9/F6rgdbxmMAKcF5lSZktPb3VA1OL8HhH0uCtYguy2vlnu5OTow/rQm0sFGzA/Q4pcC7wNhGttS5ttcW3mBSY/5wUMcipfQe5LOar5cTrBBw==

**Comment by M4Lien** [comment]
This token is changed. Please check this on your machine
Q2GaB+zq2E5fB3zz/4TWMY9YHsTDk/mW/i9unOaZVMmRBeDAsl1BRy2OA1xeGQy0fqCIsDCc/Ttz33uFgRc5EYVusMoN5z5Fd+tSyk7qZBU7SRN3Metewf1c2d4EljoT/DH/Ih+ldkjyW86vVOxGbE2BeeRBFbhQyWIkuf9Yh34rZb35FH6F420XyqzE1MlldSxbSj4nrS7xdzVR7RUBr4XK4CZ6xiq7qPSnTRkhRcnND25kQQ5dtamVhnF16WlS+jNTOuMcCrm84PTyemJeIC2b9YoKp2x5+vEaL7spGfd8Eb68lSCa26uVXXR/2iWn/cPjaWGVO9sQRYoj5Y9y2qJLHnqDs96qJXdXzH4HmFpJkkljCjE6LPcrEIIlkyQ1jtUTuZesCMPllMsKsnPyaQ==

**Comment by alexwmsoft** [comment]
I'm sorry, but I think this is the final token since the cron daemon is dead now.
Hope you can update this access token anytime when you are free. Thanks

+kI6C54aDR88lSOMS43ncb4Oa0lWR7maOLh7Or1XKaLaGi4MFoo8ksQiI8s2wk6see97gr54uW141qzWKReWiHhjdQ5HADeobvqmz/ENT/77/n6H35QTUOHbncQJdKbgO77KUkmkHu3NBfZnPY9fcyKrYdT+Q1JG6XaF1TkWOaldjBpeyUl20dW+KMPT2bqKLvsXEk2SXd1Ftavw1IQjPQ==

**Comment by alexwmsoft** [comment]
gHgWisVa3pLe1ZxFFPqlDGJ42Kdqh6tFCq1DwDVXEHRRGJFvRz/NxbGPbqVIkMI6nIhulQ2j5SULkgtUY1mEyg0r0H/aQsBKSnL9n0L2AewddwXXPlCaen7f8jJyqDfq

**Comment by M4Lien** [comment]
I changed your token on my machine.
VJAoUolePZgAlg+1BshNLNAR7IV420k39DiCzeQyRPfzXEFIml/Lpha/4wrlL4trroIuN8c3ehG7KZv0Jtfoo+IBvCqN3PhH1Kbp9IlbuSs=

**Comment by alexwmsoft** [comment]
dDUNf4CDy24tzwUoxDzxzFGKDiIQM94lsu0cPWRzNIzZ8psEaVk6Ravvjs9IdHcz
Okay, this is the latest refresh token.

**Comment by alexwmsoft** [comment]
fbwb420Emwv2OkqzJ/OChv6hEcFJMf1TeV5TGMMK4xc4atYfTPiRJa1J8bE3gNSnt2ICCHVTnLFGIyt1DhSRDjLJVsblm/Ywr2tqXJ06L9CZ9prhW9zv20MDAwhvU1Qu11zRDDUPxV4WPZGeh1COR3ABV9a0csLJXSGpT1VWBETKRa9cpdGGLbsF90yK3+KTQyw2sWKpzO17rKRbyS8J8szAtz3UYgXQ8KvxLHqqJ97qNfRm3vWGV28bzoSZVOrQ

Hi, the token is changed too. Please check.

**Comment by M4Lien** [comment]
y7WTPzgXEg7lbonTFhDnSK0Aq4w68B0ZhFLKUwve0wxAHLK20Vj1EQCLDuFgeRHUzHUONYeDGz6w2eblLxnm7su1OsMZGOV5tWj8nkk/rdZH646dL/dmASUANI0M2tWQ

**Comment by alexwmsoft** [comment]
fWUen4NZ2gCTJ+6wTK3zCrSBXlBQKun4guJzhQGeS15lN5dCxTA97HVmxmvZlopIBZPd0vzU/84kaU3I0feSw5KvPCAcWMfuNW37cqDjiSG52DjgbcqE7/epikFZb4b3xW7KWolih0CIa1gRla2Q2wEzU85EMrPg+gcBTFLxtQfMBNSjusdueNb/d+RaTjA0EFVll83H2fAyuEDBLvwRABV9Lpf0FmFzIIZxQ2TUV9fd+tZ2BhwYH07X+piByhss

**Comment by alexwmsoft** [comment]
Please check this one. 
q1zcK5CN15hcMfvl+eUDUlzaE8aPvksYSoaJnU9m9mLJ692pRjtlowxPQfUs7JwSpZkwttrvjgfYQzYuVo48Ds4MIO4sCOGcthA21PmXczI=

**Comment by M4Lien** [comment]
CVRDUIzq+Dqr4A4hXL/rvPF1ByR6EZjnvczfstS+q6OKsmJiMJNqIpIxvDn2LyqpS1V3R2nBMUxJxmL1Tey8USDbQf92IKjz/FsBVqhwdoA=
I've just updated the token that you sent

**Comment by alexwmsoft** [comment]
eVg4UYiwxQeGMp69sGsp6ZvZRZM1DFSGHg3gKbSGly2nxD3QqSNdMxIGvI8EHxxEW1br+QKXvkZgoai85jiNeAZCRaVKgBYRkGHo60gZtTU=

Hi, as the time changes, the token is refreshed automatically from the token server.

**Comment by M4Lien** [comment]
I've got it. Now it works well

**Comment by alexwmsoft** [comment]
Great!

**Comment by alexwmsoft** [comment]
0YIt2t6+jMs3ayi+dr1lnyswJEgcFPXvwzCxyqw9bleEJZX9KQ10D13FUWcWtDHPtab7yHJBm0F7hX+d2a5LffZR4P4UBGz3l/EgspHd8JEO7T5qCZbZI8pIB5XpPFnb68el7SVAVXmqyfOL88BX2kt28aB2ZPMKufMM4hum/IiAil/5+++AYNCKlMb1hJNF

**Comment by M4Lien** [comment]
fX0mZjbC8n+MayHlXknnWKcWfo5mx9+Amig0/IIHvANZeoLXz/ulXosxC7eHbKQX8BohcvK0N1m7phG5jc7629kJWhTqZWBxIMo+HpozLGSJhTgFCUKqJmRincmVsiMaFKRcugoeP42i9+sf9AsQwemV0OEZvh1kwNZY3LZ8WyTfayZgi+qNIrHYkL8g9ZsFpm4KI/rSGHo8EIEiMvkVc4jOcWC1+ybdJ32MqX9wr0Q=

**Comment by alexwmsoft** [comment]
dEcgaMxD4v+l0xtYwVz/Actgw32VN3f2zAP3FVEtat9aoOYqGDT6FsoxHWDIvsRDKnmsTDbLLLBhFvEQNRQdWNHfrU3wPgf8nBuVwqHbPPvZ0Ep2SIvOLV1jGKHq8k3IyTVTVwaqYv0LYlRFB0cE7g==

This will be the last token that should be updated. Thanks
